-- drop/create tables/sequences for PLR_HS_CATALOG schema

DROP TABLE IF EXISTS PLR_HS_CATALOG.HS_SYSTEM_OF_ORIGIN CASCADE;

CREATE TABLE PLR_HS_CATALOG.HS_SYSTEM_OF_ORIGIN (
	SYSTEM_ID BIGINT NOT NULL,
	SYSTEM_CD VARCHAR(50) NOT NULL, 
	SYSTEM_DESC_TXT VARCHAR(255) NOT NULL, 
	/*SYSTEM_LOOKUP_URL VARCHAR(2048) NULL, */
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NULL,	
	CONSTRAINT "HS_SYSTEM_ID_PK" PRIMARY KEY (SYSTEM_ID));
	
DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.HS_SYSTEM_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.HS_SYSTEM_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;


DROP TABLE IF EXISTS PLR_HS_CATALOG.CODE_SYSTEM CASCADE;

CREATE TABLE PLR_HS_CATALOG.CODE_SYSTEM (
	CODE_SYSTEM_ID BIGINT NOT NULL,
	/* CODE_SYSTEM_CD VARCHAR(50) NOT NULL, */
	CODE_SYSTEM_DESC_TXT VARCHAR(255) NOT NULL, 
	CODE_SYSTEM_LOOKUP_URL VARCHAR(2048) NULL, 
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NULL,	
	CONSTRAINT "CODE_SYSTEM_ID_PK" PRIMARY KEY (CODE_SYSTEM_ID));
	
DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.CODE_SYSTEM_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.CODE_SYSTEM_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;


DROP TABLE IF EXISTS PLR_HS_CATALOG.CATALOG_SERVICE CASCADE;

CREATE TABLE PLR_HS_CATALOG.CATALOG_SERVICE (
	CATALOG_SERVICE_ID BIGINT NOT NULL,
	SERVICE_LOGICAL_ID BIGINT NOT NULL, -- logicalId
	SERVICE_EXT_IDENT VARCHAR(50) NULL, -- store the externalID or code provided -- business Identifier
	SYSTEM_ID BIGINT NOT NULL,
	SERVICE_NAME VARCHAR(50) NOT NULL, 
	SERVICE_DESC_TXT VARCHAR(255) NOT NULL,
	PARENT_SERVICE_ID BIGINT NULL,
	COMMENTS_TXT VARCHAR(255) NULL,
	NOTES_TXT VARCHAR(255) NULL,
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NULL,	
	CONSTRAINT "CATALOG_SERVICE_ID_PK" PRIMARY KEY (CATALOG_SERVICE_ID),
	CONSTRAINT "SYSTEM_ID_FK" FOREIGN KEY (SYSTEM_ID) REFERENCES PLR_HS_CATALOG.HS_SYSTEM_OF_ORIGIN (SYSTEM_ID));
	
DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.CATALOG_SERVICE_SEQ;
DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.SERVICE_LOGICAL_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.CATALOG_SERVICE_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;
CREATE SEQUENCE PLR_HS_CATALOG.SERVICE_LOGICAL_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;

 
DROP TABLE IF EXISTS PLR_HS_CATALOG.SERVICE_TYPE_REL CASCADE;

CREATE TABLE PLR_HS_CATALOG.SERVICE_TYPE_REL (
	SERVICE_TYPE_REL_ID BIGINT NOT NULL, 
	SERVICE_TYPE_LOOKUP_CD VARCHAR(50) NOT NULL,
	CODE_SYSTEM_ID BIGINT NOT NULL,
	CATALOG_SERVICE_ID BIGINT NOT NULL, 
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NULL,	
	CONSTRAINT "SERVICE_TYPE_REL_ID_PK" PRIMARY KEY (SERVICE_TYPE_REL_ID),
	CONSTRAINT "CODE_SYSTEM_ID_FK" FOREIGN KEY (CODE_SYSTEM_ID) REFERENCES PLR_HS_CATALOG.CODE_SYSTEM (CODE_SYSTEM_ID),
	CONSTRAINT "CATALOG_SERVICE_ID_FK" FOREIGN KEY (CATALOG_SERVICE_ID) REFERENCES PLR_HS_CATALOG.CATALOG_SERVICE (CATALOG_SERVICE_ID));

DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.SERVICE_TYPE_REL_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.SERVICE_TYPE_REL_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;


DROP TABLE IF EXISTS PLR_HS_CATALOG.SPECIALTY_REL CASCADE;

CREATE TABLE PLR_HS_CATALOG.SPECIALTY_REL (
	SPECIALTY_REL_ID BIGINT NOT NULL, 
	SPECIALTY_LOOKUP_CD VARCHAR(50) NOT NULL,	
	CODE_SYSTEM_ID BIGINT NOT NULL,
	CATALOG_SERVICE_ID BIGINT NOT NULL, 
	EFFECTIVE_START_DT DATE NOT NULL,
	EFFECTIVE_END_DT DATE NULL,	
	CONSTRAINT "SPECIALTY_REL_ID_PK" PRIMARY KEY (SPECIALTY_REL_ID),
	CONSTRAINT "CODE_SYSTEM_ID_FK" FOREIGN KEY (CODE_SYSTEM_ID) REFERENCES PLR_HS_CATALOG.CODE_SYSTEM (CODE_SYSTEM_ID),
	CONSTRAINT "CATALOG_SERVICE_ID_FK" FOREIGN KEY (CATALOG_SERVICE_ID) REFERENCES PLR_HS_CATALOG.CATALOG_SERVICE (CATALOG_SERVICE_ID));

DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.SPECIALTY_REL_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.SPECIALTY_REL_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;


DROP TABLE IF EXISTS PLR_HS_CATALOG.SYSTEM_PARAMETER CASCADE;

CREATE TABLE PLR_HS_CATALOG.SYSTEM_PARAMETER (
	SYSTEM_PARAMETER_ID BIGINT NOT NULL, 
	PARAMETER_CD  VARCHAR(50) NOT NULL,	
	PARAMETER_VALUE  VARCHAR(2048) NOT NULL, 
	CONSTRAINT "SYSTEM_PARAMETER_ID_PK" PRIMARY KEY (SYSTEM_PARAMETER_ID),
	CONSTRAINT "UNIQUE_PARAM_CD" UNIQUE (PARAMETER_CD));
	
DROP SEQUENCE IF EXISTS PLR_HS_CATALOG.SYSTEM_PARAMETER_SEQ;
CREATE SEQUENCE PLR_HS_CATALOG.SYSTEM_PARAMETER_SEQ AS BIGINT MINVALUE 1 NO MAXVALUE INCREMENT BY 1 START WITH 1 CACHE 20 NO CYCLE;
