-- create PLR Services Catalogue schema in each db env.

-- only SELECT for now, will add more when we will add any admin capabilities
GRANT SELECT ON PLR_HS_CATALOG.HS_SYSTEM_OF_ORIGIN TO SERVICE_CATALOG_PROXY_ROLE;
GRANT SELECT ON PLR_HS_CATALOG.CATALOG_SERVICE TO SERVICE_CATALOG_PROXY_ROLE;
GRANT SELECT ON PLR_HS_CATALOG.SERVICE_TYPE_REL TO SERVICE_CATALOG_PROXY_ROLE;
GRANT SELECT ON PLR_HS_CATALOG.SPECIALTY_REL TO SERVICE_CATALOG_PROXY_ROLE;
GRANT SELECT ON PLR_HS_CATALOG.SYSTEM_PARAMETER TO SERVICE_CATALOG_PROXY_ROLE;



