spring:
  application:
    name: plr-service-catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/plr_hs_catalog
    username: plr_user
    password: plr_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8080
